---
- name: "Change permission(s) of an existing file."
  hosts: localhost

  tasks:
  - name: "Create a file."
    file:
      path: "/home/prithss/PrithssSpace/demo.txt"
      state: touch

  - name: "Change the persmission(s) of the file."
    file:
      path: "/home/prithss/PrithssSpace/demo.txt"
      mode: 0761
