---
- name: "Using Handlers."
  hosts: localhost
  become: yes
  
  tasks:
  - name: "Disable Nginx."
    service:
      name: "nginx"
      state: stopped
    notify: "Restart Nginx."

  handlers:
  - name: "Restart Nginx."
    service:
      name: "nginx"
      state: "reloaded"
  

  
