---
- name: "Installing Nginx on a remote device."
  hosts: all

  tasks:
  - name: "Install Nginx"
    apt:
      name: nginx
      state: present

  - name: "Start & Enable the service."
    service:  
      name: nginx
      state: started
      enabled: yes